<?php
$pageTitle = 'About BTP CloudEXCELON | BTP Innovations';
$metaDescription = 'BTP CloudEXCELON is part of the BTP Innovations ecosystem, helping clients solve technology problems through advisory, execution, and lifecycle support.';
$pagePath = '/about';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>About BTP CloudEXCELON</h1><p>BTP CloudEXCELON helps organizations plan, migrate, modernize, optimize, and manage cloud environments across Azure, AWS, Google Cloud, hybrid infrastructure, and operational platforms.</p></div></section>
<section class="section"><div class="container visual-split"><div><p class="eyebrow">Who We Are</p><h2>Part of one BTP platform, focused on a specific customer problem.</h2><p>BTP CloudEXCELON operates inside the BTP Innovations ecosystem, where advisory, sourcing, engineering, implementation, managed services, and optimization connect through one coordinated delivery model.</p><p>IT and business teams facing cloud cost pressure, migration uncertainty, architecture gaps, security concerns, or operational complexity across multi-cloud and hybrid environments.</p></div><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="CloudEXCELON ecosystem visual" loading="lazy"></figure></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Differentiators</p><h2>Advisory-led, execution-ready, and lifecycle aware.</h2></div><div class="card-grid compact"><article class="service-card"><span class="service-icon">QUA</span><h3>Quarterback Model</h3><p>One strategic relationship coordinates the right subject matter experts around each client need.</p></article><article class="service-card"><span class="service-icon">ENG</span><h3>Engineering-First IPC</h3><p>Cross-functional thinking reduces handoff gaps between security, cloud, infrastructure, software, and operations.</p></article><article class="service-card"><span class="service-icon">VEN</span><h3>Vendor-Agnostic Fit</h3><p>Recommendations are shaped around client requirements, not a single vendor agenda.</p></article><article class="service-card"><span class="service-icon">LIF</span><h3>Lifecycle Support</h3><p>BTP stays focused beyond the initial decision so execution, support, and optimization remain connected.</p></article></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">ManageSP</p><h3>Managed IT services that keep operations supported after deployment.</h3><a href="https://managesp.cloudexcelon.com/">BTP ManageSP <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">DatastAIsis</p><h3>AI, automation, analytics, and operational intelligence for business outcomes.</h3><a href="https://datastaisis.cloudexcelon.com/">BTP DatastAIsis <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Talk With BTP</p><h2>Get clear guidance before the next decision becomes expensive.</h2><p>Cloud architecture and infrastructure built for scalable enterprise environments.</p></div><a class="button button-primary" href="/contact">Discuss Your Cloud Roadmap</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
