<?php
$pageTitle = 'BTP CloudEXCELON | Cloud architecture built for scale, resilience, and operational clarity.';
$metaDescription = 'BTP CloudEXCELON helps organizations plan, migrate, modernize, optimize, and manage cloud environments across Azure, AWS, Google Cloud, hybrid infrastructure, and operational platforms.';
$pagePath = '/';
require __DIR__ . '/includes/header.php';
?>
<section class="hero hero-home"><div class="hero-copy"><p class="eyebrow">BTP CloudEXCELON</p><h1>Cloud architecture built for scale, resilience, and operational clarity.</h1><p>BTP CloudEXCELON helps organizations plan, migrate, modernize, optimize, and manage cloud environments across Azure, AWS, Google Cloud, hybrid infrastructure, and operational platforms.</p><div class="actions"><a class="button button-primary" href="/contact">Discuss Your Cloud Roadmap <span aria-hidden="true">&rarr;</span></a><a class="button button-outline" href="/services">Explore Services <span aria-hidden="true">&rarr;</span></a></div><div class="hero-proof"><span>Advisory-first</span><span>Vendor-aware</span><span>Execution-ready</span></div></div><div class="hero-visual"><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="CloudEXCELON enterprise service visual"></figure></div></section>
<section class="section services-preview"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Clear service paths without a long discovery maze.</h2></div><div class="card-grid compact"><article class="service-card"><span class="service-icon">CS</span><h3>Cloud strategy</h3><p>Clarifies options, tradeoffs, and executive next steps before teams commit time or budget.</p></article><article class="service-card"><span class="service-icon">CM</span><h3>Cloud migration</h3><p>Turns the plan into sequenced work with clearer ownership, dependencies, and delivery checkpoints.</p></article><article class="service-card"><span class="service-icon">CO</span><h3>Cloud optimization</h3><p>Defines scope, fit, risks, and next actions so the service can move from idea to execution.</p></article><article class="service-card"><span class="service-icon">CI</span><h3>Cloud infrastructure</h3><p>Defines scope, fit, risks, and next actions so the service can move from idea to execution.</p></article><article class="service-card"><span class="service-icon">AA</span><h3>Azure advisory</h3><p>Clarifies options, tradeoffs, and executive next steps before teams commit time or budget.</p></article><article class="service-card"><span class="service-icon">AA</span><h3>AWS advisory</h3><p>Clarifies options, tradeoffs, and executive next steps before teams commit time or budget.</p></article></div></div></section>
<section class="section color-band"><div class="container visual-split"><div><p class="eyebrow">Why Choose Us</p><h2>Revenue comes from cloud migration, infrastructure architecture, optimization, and managed cloud planning.</h2><p>IT and business teams facing cloud cost pressure, migration uncertainty, architecture gaps, security concerns, or operational complexity across multi-cloud and hybrid environments.</p><div class="mini-proof"><article><strong>Scalable cloud foundations</strong><span>Outcome-focused support.</span></article><article><strong>Better cost control</strong><span>Outcome-focused support.</span></article><article><strong>Improved resilience</strong><span>Outcome-focused support.</span></article></div></div><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="CloudEXCELON trust visual" loading="lazy"></figure></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="CloudEXCELON process visual" loading="lazy"></figure><div><p class="eyebrow">Process</p><h2>Simple enough to start, structured enough to scale.</h2><div class="process-grid compact"><article><span>01</span><h3>Assess the environment</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Design the architecture</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Plan the migration</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Deploy and validate</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">ManageSP</p><h3>Managed IT services that keep operations supported after deployment.</h3><a href="https://managesp.cloudexcelon.com/">BTP ManageSP <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">DatastAIsis</p><h3>AI, automation, analytics, and operational intelligence for business outcomes.</h3><a href="https://datastaisis.cloudexcelon.com/">BTP DatastAIsis <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Step</p><h2>Ready to make the technology path clearer?</h2><p>BTP CloudEXCELON helps organizations plan, migrate, modernize, optimize, and manage cloud environments across Azure, AWS, Google Cloud, hybrid infrastructure, and operational platforms.</p></div><a class="button button-primary" href="/contact">Discuss Your Cloud Roadmap <span aria-hidden="true">&rarr;</span></a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
