<?php
$pageTitle = 'BTP ManageSP | Managed IT support that keeps business technology stable after launch.';
$metaDescription = 'BTP ManageSP provides operational support, infrastructure management, cloud operations, end-user support, vendor coordination, and lifecycle management for business technology environments.';
$pagePath = '/';
require __DIR__ . '/includes/header.php';
?>
<section class="hero hero-home"><div class="hero-copy"><p class="eyebrow">BTP ManageSP</p><h1>Managed IT support that keeps business technology stable after launch.</h1><p>BTP ManageSP provides operational support, infrastructure management, cloud operations, end-user support, vendor coordination, and lifecycle management for business technology environments.</p><div class="actions"><a class="button button-primary" href="/contact">Request Support <span aria-hidden="true">&rarr;</span></a><a class="button button-outline" href="/services">Explore Services <span aria-hidden="true">&rarr;</span></a></div><div class="hero-proof"><span>Advisory-first</span><span>Vendor-aware</span><span>Execution-ready</span></div></div><div class="hero-visual"><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="ManageSP enterprise service visual"></figure></div></section>
<section class="section services-preview"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Clear service paths without a long discovery maze.</h2></div><div class="card-grid compact"><article class="service-card"><span class="service-icon">MIS</span><h3>Managed IT services</h3><p>Creates a more reliable operating model with routing, coverage, and escalation clarity.</p></article><article class="service-card"><span class="service-icon">IO</span><h3>IT operations</h3><p>Creates a more reliable operating model with routing, coverage, and escalation clarity.</p></article><article class="service-card"><span class="service-icon">IS</span><h3>Infrastructure support</h3><p>Creates a more reliable operating model with routing, coverage, and escalation clarity.</p></article><article class="service-card"><span class="service-icon">CO</span><h3>Cloud operations</h3><p>Creates a more reliable operating model with routing, coverage, and escalation clarity.</p></article><article class="service-card"><span class="service-icon">EUS</span><h3>End-user support</h3><p>Creates a more reliable operating model with routing, coverage, and escalation clarity.</p></article><article class="service-card"><span class="service-icon">VC</span><h3>Vendor coordination</h3><p>Defines scope, fit, risks, and next actions so the service can move from idea to execution.</p></article></div></div></section>
<section class="section color-band"><div class="container visual-split"><div><p class="eyebrow">Why Choose Us</p><h2>Revenue comes from managed IT operations, support coverage, vendor coordination, and lifecycle management.</h2><p>Organizations with limited internal IT capacity, fragmented support providers, growing cloud operations, or systems that need consistent management after deployment.</p><div class="mini-proof"><article><strong>More reliable operations</strong><span>Outcome-focused support.</span></article><article><strong>Faster issue routing</strong><span>Outcome-focused support.</span></article><article><strong>Clearer ownership</strong><span>Outcome-focused support.</span></article></div></div><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="ManageSP trust visual" loading="lazy"></figure></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="ManageSP process visual" loading="lazy"></figure><div><p class="eyebrow">Process</p><h2>Simple enough to start, structured enough to scale.</h2><div class="process-grid compact"><article><span>01</span><h3>Review environment</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Define support needs</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Stabilize operations</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Coordinate vendors</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">PraaS</p><h3>Procurement and sourcing support that simplifies technology acquisition through one coordinated path.</h3><a href="https://praas.cloudexcelon.com/">BTP PraaS <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Step</p><h2>Ready to make the technology path clearer?</h2><p>BTP ManageSP provides operational support, infrastructure management, cloud operations, end-user support, vendor coordination, and lifecycle management for business technology environments.</p></div><a class="button button-primary" href="/contact">Request Support <span aria-hidden="true">&rarr;</span></a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
