---
deployment:
  tasks:
    - export DEPLOYPATH=/home/USERNAME/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
