<?php
$pageTitle = 'About BTP TechAdvisors | BTP Innovations';
$metaDescription = 'BTP TechAdvisors is part of the BTP Innovations ecosystem, helping clients solve technology problems through advisory, execution, and lifecycle support.';
$pagePath = '/about';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Who We Are</p><h1>About BTP TechAdvisors</h1><p>BTP TechAdvisors helps leaders evaluate technology options, clarify tradeoffs, prioritize roadmaps, and move from strategy to accountable execution.</p><div class="actions"><a class="button button-primary" href="/contact">Talk to an Advisor</a><a class="button button-outline" href="/services">View Services</a></div></div><figure class="visual-card"><img src="<?= e(asset('images/about-visual.svg')) ?>" alt="TechAdvisors page hero visual"></figure></div></section>
<section class="section"><div class="container"><div class="belief-grid"><article><p class="eyebrow">Mission</p><h2>Make complex technology decisions easier to buy, launch, support, and improve.</h2><p>BTP TechAdvisors operates inside the BTP Innovations ecosystem, where advisory, sourcing, engineering, implementation, managed services, and optimization connect through one coordinated delivery model.</p></article><article><p class="eyebrow">Vision</p><h2>One BTP ecosystem for the full technology journey.</h2><p>Clients should not have to stitch together disconnected vendors just to define scope, compare options, execute work, and keep systems supported after launch.</p></article><article><p class="eyebrow">Values</p><h2>Clarity, accountability, and practical execution.</h2><p>BTP focuses on fit, transparency, stakeholder alignment, measurable outcomes, and recommendations that can move beyond a slide deck.</p></article></div></div></section>
<section class="section muted"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="TechAdvisors ecosystem visual" loading="lazy"></figure><div><p class="eyebrow">Why Clients Choose BTP</p><h2>Advisory-led, execution-ready, and lifecycle aware.</h2><p>Executives, IT leaders, operations teams, and finance stakeholders making decisions across cloud, cybersecurity, AI, managed IT, communications, and software platforms.</p><div class="benefit-grid"><article class="service-card"><span class="service-icon">QUA</span><h3>Quarterback Model</h3><p>One strategic relationship coordinates the right subject matter experts around each client need.</p></article><article class="service-card"><span class="service-icon">ENG</span><h3>Engineering-First IPC</h3><p>Cross-functional thinking reduces handoff gaps between security, cloud, infrastructure, software, and operations.</p></article><article class="service-card"><span class="service-icon">VEN</span><h3>Vendor-Agnostic Fit</h3><p>Recommendations are shaped around client requirements, not a single vendor agenda.</p></article><article class="service-card"><span class="service-icon">LIF</span><h3>Lifecycle Support</h3><p>BTP stays focused beyond the initial decision so execution, support, and optimization remain connected.</p></article></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading centered"><p class="eyebrow">How We Work</p><h2>Designed around the buyer journey from learning to proposal.</h2></div><div class="journey-grid"><article><span>Learn</span><p>Clear service definitions and business outcomes help visitors understand fit quickly.</p></article><article><span>Trust</span><p>BTP ecosystem positioning, process detail, and deliverables reduce perceived risk.</p></article><article><span>Contact</span><p>The form captures the business need without forcing a premature technical scope.</p></article><article><span>Discovery Call</span><p>BTP clarifies goals, urgency, constraints, current vendors, and next-step ownership.</p></article><article><span>Proposal</span><p>The recommended path is shaped around the service model, delivery plan, and measurable outcome.</p></article></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">PraaS</p><h3>Procurement and sourcing support that simplifies technology acquisition through one coordinated path.</h3><a href="https://praas.cloudexcelon.com/">BTP PraaS <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="trust-wall"><div class="container"><p class="eyebrow">Trust Signals</p><div class="trust-grid"><article><span>VOB</span><strong>Veteran-Owned Business</strong></article><article><span>MPA</span><strong>Microsoft Partner Alignment</strong></article><article><span>UBS</span><strong>US-Based Support</strong></article><article><span>ES</span><strong>Enterprise Solutions</strong></article><article><span>SD</span><strong>Scalable Delivery</strong></article><article><span>TE</span><strong>TechAdvisors Expertise</strong></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Talk With BTP</p><h2>Get clear guidance before the next decision becomes expensive.</h2><p>Strategic advisory and client engagement for complex technology decisions.</p></div><a class="button button-primary" href="/contact">Talk to an Advisor</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
