<?php
$pageTitle = 'About BTP DatastAIsis | BTP Innovations';
$metaDescription = 'BTP DatastAIsis is part of the BTP Innovations ecosystem, helping clients solve technology problems through advisory, execution, and lifecycle support.';
$pagePath = '/about';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Who We Are</p><h1>About BTP DatastAIsis</h1><p>BTP DatastAIsis helps organizations structure data, automate repetitive workflows, build analytics, and apply AI to improve decisions and business outcomes.</p><div class="actions"><a class="button button-primary" href="/contact">Plan an AI and Data Session</a><a class="button button-outline" href="/services">View Services</a></div></div><figure class="visual-card"><img src="<?= e(asset('images/about-visual.svg')) ?>" alt="DatastAIsis page hero visual"></figure></div></section>
<section class="section"><div class="container"><div class="belief-grid"><article><p class="eyebrow">Mission</p><h2>Make complex technology decisions easier to buy, launch, support, and improve.</h2><p>BTP DatastAIsis operates inside the BTP Innovations ecosystem, where advisory, sourcing, engineering, implementation, managed services, and optimization connect through one coordinated delivery model.</p></article><article><p class="eyebrow">Vision</p><h2>One BTP ecosystem for the full technology journey.</h2><p>Clients should not have to stitch together disconnected vendors just to define scope, compare options, execute work, and keep systems supported after launch.</p></article><article><p class="eyebrow">Values</p><h2>Clarity, accountability, and practical execution.</h2><p>BTP focuses on fit, transparency, stakeholder alignment, measurable outcomes, and recommendations that can move beyond a slide deck.</p></article></div></div></section>
<section class="section muted"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="DatastAIsis ecosystem visual" loading="lazy"></figure><div><p class="eyebrow">Why Clients Choose BTP</p><h2>Advisory-led, execution-ready, and lifecycle aware.</h2><p>Teams with scattered reporting, manual processes, inconsistent data, limited visibility, or AI interest that needs practical use cases and controlled implementation.</p><div class="benefit-grid"><article class="service-card"><span class="service-icon">QUA</span><h3>Quarterback Model</h3><p>One strategic relationship coordinates the right subject matter experts around each client need.</p></article><article class="service-card"><span class="service-icon">ENG</span><h3>Engineering-First IPC</h3><p>Cross-functional thinking reduces handoff gaps between security, cloud, infrastructure, software, and operations.</p></article><article class="service-card"><span class="service-icon">VEN</span><h3>Vendor-Agnostic Fit</h3><p>Recommendations are shaped around client requirements, not a single vendor agenda.</p></article><article class="service-card"><span class="service-icon">LIF</span><h3>Lifecycle Support</h3><p>BTP stays focused beyond the initial decision so execution, support, and optimization remain connected.</p></article></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading centered"><p class="eyebrow">How We Work</p><h2>Designed around the buyer journey from learning to proposal.</h2></div><div class="journey-grid"><article><span>Learn</span><p>Clear service definitions and business outcomes help visitors understand fit quickly.</p></article><article><span>Trust</span><p>BTP ecosystem positioning, process detail, and deliverables reduce perceived risk.</p></article><article><span>Contact</span><p>The form captures the business need without forcing a premature technical scope.</p></article><article><span>Discovery Call</span><p>BTP clarifies goals, urgency, constraints, current vendors, and next-step ownership.</p></article><article><span>Proposal</span><p>The recommended path is shaped around the service model, delivery plan, and measurable outcome.</p></article></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">CodeIGNITE</p><h3>Software development and application engineering for platform innovation.</h3><a href="https://codeignite.cloudexcelon.com/">BTP CodeIGNITE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="trust-wall"><div class="container"><div class="section-heading"><p class="eyebrow">Trust Signals</p><h2>Service confidence without inflated claims.</h2></div><div class="trust-grid"><article><span>DE</span><div><strong>Dedicated Expertise</strong><p>Specialized guidance aligned to the service lane and business objective.</p></div></article><article><span>SD</span><div><strong>Structured Delivery</strong><p>Discovery, planning, execution, and handoff steps stay visible.</p></div></article><article><span>SE</span><div><strong>Scalable Engagement</strong><p>Support can start focused and expand as scope becomes clearer.</p></div></article><article><span>SG</span><div><strong>Strategic Guidance</strong><p>Recommendations are shaped around fit, risk, and timing.</p></div></article><article><span>LTP</span><div><strong>Long-Term Partnership</strong><p>BTP keeps lifecycle support and future optimization in view.</p></div></article><article><span>DM</span><div><strong>DatastAIsis Methods</strong><p>Brand-specific workflows support the work customers actually need.</p></div></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Talk With BTP</p><h2>Get clear guidance before the next decision becomes expensive.</h2><p>AI, automation, analytics, and operational intelligence for business outcomes.</p></div><a class="button button-primary" href="/contact">Plan an AI and Data Session</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
