<?php
$pageTitle = 'Contact BTP DatastAIsis | Start a Conversation';
$metaDescription = 'Contact BTP DatastAIsis to discuss business needs, service questions, assessments, sourcing, support, or project planning.';
$pagePath = '/contact';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Contact</p><h1>Contact BTP DatastAIsis</h1><p>Start with one business inquiry. BTP will route the conversation to the right advisory, sourcing, engineering, or support path.</p><div class="actions"><a class="button button-primary" href="<?= e(site_url('contact')) ?>">Plan an AI and Data Session</a><a class="button button-outline" href="<?= e(site_url('services')) ?>">View Services</a></div></div><figure class="visual-card"><img src="<?= e(asset('images/contact-visual.svg')) ?>" alt="DatastAIsis page hero visual" width="880" height="560" decoding="async"></figure></div></section>
<section class="section contact-section"><div class="container contact-grid"><form id="btp-lead-form" class="contact-form" method="post" action="<?= e(site_url('contact.php')) ?>"><input type="hidden" name="brand" value="BTP DatastAIsis"><label for="full_name">Name<input id="full_name" name="full_name" autocomplete="name" required></label><label for="company_name">Company<input id="company_name" name="company_name" autocomplete="organization"></label><label for="email">Email<input id="email" type="email" name="email" autocomplete="email" required></label><label for="phone">Phone<input id="phone" name="phone" autocomplete="tel"></label><label class="full" for="message">Message<textarea id="message" name="message" rows="5" required></textarea></label><!-- TODO: Connect this form to Microsoft Forms, Power Automate, Dynamics 365, HubSpot, Salesforce, or SMTP/PHP mail when production routing is selected. --><button class="button button-primary full" type="submit">Plan an AI and Data Session</button></form><aside class="contact-panel"><h2>Business Inquiries</h2><p>AI, automation, analytics, and operational intelligence for business outcomes.</p><p><strong>Email</strong><br>info@btpinnovations.com</p><p><strong>Phone</strong><br>(800) 781-6632</p><p><strong>Address</strong><br>276 5th Avenue Suite 704<br>New York, NY 10001</p><p><strong>Business Hours</strong><br>Monday-Friday, 8:30 AM-6:00 PM Eastern</p><figure class="visual-card"><img src="<?= e(asset('images/contact-visual.svg')) ?>" alt="DatastAIsis contact visual" width="880" height="560" decoding="async" loading="lazy"></figure></aside></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Why Contact Us</p><h2>Use the form when a decision, project, vendor, or support need needs structure.</h2></div><div class="card-grid compact"><article class="service-card"><span class="service-icon">CS</span><h3>Clarify Scope</h3><p>Use the form when the business goal is clear but requirements, ownership, or technical dependencies still need structure.</p></article><article class="service-card"><span class="service-icon">CO</span><h3>Compare Options</h3><p>Ask BTP to help evaluate vendors, service models, delivery paths, or support alternatives before committing budget.</p></article><article class="service-card"><span class="service-icon">PNS</span><h3>Plan Next Steps</h3><p>Share current timing, constraints, and decision pressure so BTP can route the inquiry to the right engagement path.</p></article></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">CodeIGNITE</p><h3>Software development and application engineering for platform innovation.</h3><a href="https://codeignite.cloudexcelon.com/">BTP CodeIGNITE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Response Expectations</p><h2>Send the inquiry and BTP will route it to the right path.</h2><p>Use the form for service questions, assessments, sourcing, projects, or operational support needs. A BTP representative can use your message to prepare a focused discovery conversation.</p></div><a class="button button-primary" href="mailto:info@btpinnovations.com">Email BTP</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
