<?php
$pageTitle = 'BTP ManageSP Insights | BTP Innovations';
$metaDescription = 'Read practical ManageSP insights for business and technology leaders evaluating service decisions.';
$pagePath = '/news';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Insights</p><h1>ManageSP Insights</h1><p>Short updates and decision guides for leaders evaluating managed it services that keep operations supported after deployment.</p><div class="actions"><a class="button button-primary" href="<?= e(site_url('contact')) ?>">Request Support</a><a class="button button-outline" href="<?= e(site_url('services')) ?>">View Services</a></div></div><figure class="visual-card"><img src="<?= e(asset('images/news-visual.svg')) ?>" alt="ManageSP page hero visual"></figure></div></section>
<section class="section"><div class="container"><div class="filter-row"><span>Strategy</span><span>Operations</span><span>Risk</span><span>Optimization</span></div><article class="featured-article"><div><p class="eyebrow">Featured Article</p><h2>How leaders can evaluate ManageSP readiness before budget is committed</h2><p>A practical look at the questions, risks, stakeholders, and deliverables that should be clarified before a ManageSP engagement moves into proposal, vendor selection, or execution.</p><a class="button button-secondary" href="<?= e(site_url('contact')) ?>">Request a briefing</a></div><figure class="visual-card"><img src="<?= e(asset('images/proof-visual.svg')) ?>" alt="ManageSP featured insight visual" loading="lazy"></figure></article><div class="news-grid"><article class="news-card"><p class="eyebrow">Insight</p><h2>How to evaluate ManageSP readiness</h2><p>A concise guide for leaders deciding whether the current environment, team, or vendor model is ready for change.</p><a href="<?= e(site_url('contact')) ?>">Discuss this topic <span aria-hidden="true">&rarr;</span></a></article><article class="news-card"><p class="eyebrow">Insight</p><h2>Reducing risk before the proposal stage</h2><p>Why clearer requirements, ownership, and sequencing make enterprise technology decisions easier to approve.</p><a href="<?= e(site_url('contact')) ?>">Discuss this topic <span aria-hidden="true">&rarr;</span></a></article><article class="news-card"><p class="eyebrow">Insight</p><h2>When to bring BTP into the conversation</h2><p>Signals that a project, sourcing need, support gap, or strategy question needs coordinated advisory support.</p><a href="<?= e(site_url('contact')) ?>">Discuss this topic <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section color-band"><div class="container newsletter-card"><div><p class="eyebrow">Newsletter</p><h2>Get practical BTP decision notes.</h2><p>Use the contact form to request updates tied to your service area, industry, and current technology priorities.</p></div><a class="button button-primary" href="<?= e(site_url('contact')) ?>">Request Support</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
