<?php
$pageTitle = 'BTP CloudEXCELON Services | Cloud architecture and infrastructure built for scalable enterprise environments.';
$metaDescription = 'Explore BTP CloudEXCELON capabilities, deliverables, engagement process, and business outcomes.';
$pagePath = '/services';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>CloudEXCELON Services</h1><p>Cloud architecture and infrastructure built for scalable enterprise environments.</p></div></section>
<section class="section"><div class="container visual-split"><div><p class="eyebrow">Overview</p><h2>Cloud architecture built for scale, resilience, and operational clarity.</h2><p>BTP CloudEXCELON helps organizations plan, migrate, modernize, optimize, and manage cloud environments across Azure, AWS, Google Cloud, hybrid infrastructure, and operational platforms.</p><p><strong>Who it helps:</strong> IT and business teams facing cloud cost pressure, migration uncertainty, architecture gaps, security concerns, or operational complexity across multi-cloud and hybrid environments.</p></div><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="CloudEXCELON service visual" loading="lazy"></figure></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Summarized clearly for faster evaluation.</h2></div><div class="detail-grid compact"><article class="detail-card"><span class="service-icon">CS</span><h3>Cloud strategy</h3><p>Cloud readiness review</p></article><article class="detail-card"><span class="service-icon">CM</span><h3>Cloud migration</h3><p>Target architecture</p></article><article class="detail-card"><span class="service-icon">CO</span><h3>Cloud optimization</h3><p>Migration and modernization roadmap</p></article><article class="detail-card"><span class="service-icon">CI</span><h3>Cloud infrastructure</h3><p>Cost optimization recommendations</p></article><article class="detail-card"><span class="service-icon">AA</span><h3>Azure advisory</h3><p>Operations transition plan</p></article><article class="detail-card"><span class="service-icon">AA</span><h3>AWS advisory</h3><p>Cloud readiness review</p></article></div></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="CloudEXCELON engagement visual" loading="lazy"></figure><div><p class="eyebrow">Engagement Process</p><h2>How BTP moves from need to next step.</h2><div class="process-grid compact"><article><span>01</span><h3>Assess the environment</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Design the architecture</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Plan the migration</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Deploy and validate</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section trust-band"><div class="container proof-grid"><article><strong>Scalable cloud foundations</strong><span>Outcome-focused support.</span></article><article><strong>Better cost control</strong><span>Outcome-focused support.</span></article><article><strong>Improved resilience</strong><span>Outcome-focused support.</span></article><article><strong>Cleaner operations</strong><span>Outcome-focused support.</span></article></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Steps</p><h2>Discuss the service path that fits your environment.</h2><p>Bring your current goals, constraints, vendors, systems, or project questions. BTP will help clarify the path forward.</p></div><a class="button button-primary" href="/contact">Discuss Your Cloud Roadmap</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
