<?php
$pageTitle = 'Contact BTP SecuriSCOPE | Start a Conversation';
$metaDescription = 'Contact BTP SecuriSCOPE to discuss business needs, service questions, assessments, sourcing, support, or project planning.';
$pagePath = '/contact';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>Contact BTP SecuriSCOPE</h1><p>Start with one business inquiry. BTP will route the conversation to the right advisory, sourcing, engineering, or support path.</p></div></section>
<section class="section contact-section"><div class="container contact-grid"><form id="btp-lead-form" class="contact-form" method="post" action="/contact.php"><input type="hidden" name="brand" value="BTP SecuriSCOPE"><label for="full_name">Name<input id="full_name" name="full_name" autocomplete="name" required></label><label for="company_name">Company<input id="company_name" name="company_name" autocomplete="organization"></label><label for="email">Email<input id="email" type="email" name="email" autocomplete="email" required></label><label for="phone">Phone<input id="phone" name="phone" autocomplete="tel"></label><label class="full" for="message">Message<textarea id="message" name="message" rows="5" required></textarea></label><!-- TODO: Connect this form to Microsoft Forms, Power Automate, Dynamics 365, HubSpot, Salesforce, or SMTP/PHP mail when production routing is selected. --><button class="button button-primary full" type="submit">Start Your Assessment</button></form><aside class="contact-panel"><h2>Business Inquiries</h2><p>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</p><p><strong>Email</strong><br>info@btpinnovations.com</p><p><strong>Phone</strong><br>(800) 781-6632</p><p><strong>Address</strong><br>276 5th Avenue Suite 704<br>New York, NY 10001</p><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="SecuriSCOPE contact visual" loading="lazy"></figure></aside></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Step</p><h2>Send the inquiry and BTP will route it to the right path.</h2><p>Use the form for service questions, assessments, sourcing, projects, or operational support needs.</p></div><a class="button button-primary" href="mailto:info@btpinnovations.com">Email BTP</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
