<?php
$pageTitle = 'BTP PraaS | Technology procurement and sourcing support without vendor noise.';
$metaDescription = 'BTP PraaS helps organizations source technology products, services, licenses, vendors, and technical resources through one coordinated advisory-led path.';
$pagePath = '/';
require __DIR__ . '/includes/header.php';
?>
<section class="hero hero-home"><div class="hero-copy"><p class="eyebrow">BTP PraaS</p><h1>Technology procurement and sourcing support without vendor noise.</h1><p>BTP PraaS helps organizations source technology products, services, licenses, vendors, and technical resources through one coordinated advisory-led path.</p><div class="actions"><a class="button button-primary" href="/contact">Schedule a Sourcing Consultation <span aria-hidden="true">&rarr;</span></a><a class="button button-outline" href="/services">Explore Services <span aria-hidden="true">&rarr;</span></a></div></div><div class="hero-visual" aria-hidden="true"><div class="system-diagram"><span></span><span></span><span></span><span></span></div></div></section>
<section class="section intro-band"><div class="container two-column"><div><p class="eyebrow">BTP Innovations Ecosystem</p><h2>Procurement and sourcing support that simplifies technology acquisition through one coordinated path.</h2></div><div><p>BTP PraaS helps organizations source technology products, services, licenses, vendors, and technical resources through one coordinated advisory-led path.</p><p>Operations, IT, finance, and business leaders who need better buying decisions, cleaner vendor coordination, and a practical path from need to solution.</p></div></div></section>
<section class="section services-preview"><div class="container split-intro"><div class="section-heading"><p class="eyebrow">Core Capabilities</p><h2>Practical service areas built around outcomes.</h2><p>Each capability is structured around discovery, recommendation, implementation support, and measurable business value.</p><a class="button button-secondary" href="/services">View Services <span aria-hidden="true">&rarr;</span></a></div><div class="card-grid"><article class="service-card"><span class="service-icon">TEC</span><h3>Technology procurement</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article><article class="service-card"><span class="service-icon">VEN</span><h3>Vendor sourcing</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article><article class="service-card"><span class="service-icon">SAA</span><h3>SaaS and licensing review</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article><article class="service-card"><span class="service-icon">IT </span><h3>IT cost optimization</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article><article class="service-card"><span class="service-icon">PAR</span><h3>Partner ecosystem access</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article><article class="service-card"><span class="service-icon">RES</span><h3>Resource-as-a-Service alignment</h3><p>Designed to clarify requirements, reduce uncertainty, and move the business toward a practical next step.</p></article></div></div></section>
<section class="section process-band"><div class="container"><div class="section-heading centered"><p class="eyebrow">Engagement Process</p><h2>From first conversation to accountable next steps.</h2></div><div class="process-grid"><article><span>01</span><h3>Define the need</h3><p>Each step keeps the business objective, technical requirement, and delivery path aligned.</p></article><article><span>02</span><h3>Map viable providers</h3><p>Each step keeps the business objective, technical requirement, and delivery path aligned.</p></article><article><span>03</span><h3>Compare price and fit</h3><p>Each step keeps the business objective, technical requirement, and delivery path aligned.</p></article><article><span>04</span><h3>Coordinate selection</h3><p>Each step keeps the business objective, technical requirement, and delivery path aligned.</p></article><article><span>05</span><h3>Support the handoff</h3><p>Each step keeps the business objective, technical requirement, and delivery path aligned.</p></article></div></div></section>
<section class="section trust-band"><div class="container proof-grid"><article><strong>Faster technology acquisition</strong><span>Outcome-focused support for business and technology leaders.</span></article><article><strong>Better cost visibility</strong><span>Outcome-focused support for business and technology leaders.</span></article><article><strong>Reduced vendor management burden</strong><span>Outcome-focused support for business and technology leaders.</span></article><article><strong>Clearer accountability</strong><span>Outcome-focused support for business and technology leaders.</span></article></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Keep the work inside one connected ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">TechAdvisors</p><h3>Strategic advisory and client engagement for complex technology decisions.</h3><a href="https://techadvisors.cloudexcelon.com/">BTP TechAdvisors <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">ManageSP</p><h3>Managed IT services that keep operations supported after deployment.</h3><a href="https://managesp.cloudexcelon.com/">BTP ManageSP <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Step</p><h2>Ready to make the technology path clearer?</h2><p>BTP PraaS helps organizations source technology products, services, licenses, vendors, and technical resources through one coordinated advisory-led path.</p></div><a class="button button-primary" href="/contact">Schedule a Sourcing Consultation <span aria-hidden="true">&rarr;</span></a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
