<?php
$pageTitle = 'BTP PraaS Services | Procurement and sourcing support that simplifies technology acquisition through one coordinated path.';
$metaDescription = 'Explore BTP PraaS capabilities, deliverables, engagement process, and business outcomes.';
$pagePath = '/services';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>PraaS Services</h1><p>Procurement and sourcing support that simplifies technology acquisition through one coordinated path.</p></div></section>
<section class="section"><div class="container visual-split"><div><p class="eyebrow">Overview</p><h2>Technology procurement and sourcing support without vendor noise.</h2><p>BTP PraaS helps organizations source technology products, services, licenses, vendors, and technical resources through one coordinated advisory-led path.</p><p><strong>Who it helps:</strong> Operations, IT, finance, and business leaders who need better buying decisions, cleaner vendor coordination, and a practical path from need to solution.</p></div><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="PraaS service visual" loading="lazy"></figure></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Summarized clearly for faster evaluation.</h2></div><div class="detail-grid compact"><article class="detail-card"><span class="service-icon">TP</span><h3>Technology procurement</h3><p>Requirement and budget summary</p></article><article class="detail-card"><span class="service-icon">VS</span><h3>Vendor sourcing</h3><p>Vendor and option comparison</p></article><article class="detail-card"><span class="service-icon">SAL</span><h3>SaaS and licensing review</h3><p>Pricing and feature review</p></article><article class="detail-card"><span class="service-icon">ICO</span><h3>IT cost optimization</h3><p>Recommended sourcing path</p></article><article class="detail-card"><span class="service-icon">PEA</span><h3>Partner ecosystem access</h3><p>Implementation handoff notes</p></article><article class="detail-card"><span class="service-icon">RAA</span><h3>Resource-as-a-Service alignment</h3><p>Requirement and budget summary</p></article></div></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="PraaS engagement visual" loading="lazy"></figure><div><p class="eyebrow">Engagement Process</p><h2>How BTP moves from need to next step.</h2><div class="process-grid compact"><article><span>01</span><h3>Define the need</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Map viable providers</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Compare price and fit</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Coordinate selection</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section trust-band"><div class="container proof-grid"><article><strong>Faster technology acquisition</strong><span>Outcome-focused support.</span></article><article><strong>Better cost visibility</strong><span>Outcome-focused support.</span></article><article><strong>Reduced vendor management burden</strong><span>Outcome-focused support.</span></article><article><strong>Clearer accountability</strong><span>Outcome-focused support.</span></article></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Steps</p><h2>Discuss the service path that fits your environment.</h2><p>Bring your current goals, constraints, vendors, systems, or project questions. BTP will help clarify the path forward.</p></div><a class="button button-primary" href="/contact">Schedule a Sourcing Consultation</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
