<?php
$pageTitle = 'BTP DatastAIsis | AI, automation, and analytics that turn scattered work into operational intelligence.';
$metaDescription = 'BTP DatastAIsis helps organizations structure data, automate repetitive workflows, build analytics, and apply AI to improve decisions and business outcomes.';
$pagePath = '/';
require __DIR__ . '/includes/header.php';
?>
<section class="hero hero-home"><div class="hero-copy"><p class="eyebrow">BTP DatastAIsis</p><h1>AI, automation, and analytics that turn scattered work into operational intelligence.</h1><p>BTP DatastAIsis helps organizations structure data, automate repetitive workflows, build analytics, and apply AI to improve decisions and business outcomes.</p><div class="actions"><a class="button button-primary" href="/contact">Plan an AI and Data Session <span aria-hidden="true">&rarr;</span></a><a class="button button-outline" href="/services">Explore Services <span aria-hidden="true">&rarr;</span></a></div><div class="hero-proof"><span>Advisory-first</span><span>Vendor-aware</span><span>Execution-ready</span></div></div><div class="hero-visual"><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="DatastAIsis enterprise service visual"></figure></div></section>
<section class="section services-preview"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Clear service paths without a long discovery maze.</h2></div><div class="card-grid compact"><article class="service-card"><span class="service-icon">AS</span><h3>AI solutions</h3><p>Connects data, workflows, and decision points so teams can act with better visibility.</p></article><article class="service-card"><span class="service-icon">DA</span><h3>Data analytics</h3><p>Connects data, workflows, and decision points so teams can act with better visibility.</p></article><article class="service-card"><span class="service-icon">WA</span><h3>Workflow automation</h3><p>Connects data, workflows, and decision points so teams can act with better visibility.</p></article><article class="service-card"><span class="service-icon">BI</span><h3>Business intelligence</h3><p>Defines scope, fit, risks, and next actions so the service can move from idea to execution.</p></article><article class="service-card"><span class="service-icon">WO</span><h3>Workflow optimization</h3><p>Defines scope, fit, risks, and next actions so the service can move from idea to execution.</p></article><article class="service-card"><span class="service-icon">DS</span><h3>Data strategy</h3><p>Clarifies options, tradeoffs, and executive next steps before teams commit time or budget.</p></article></div></div></section>
<section class="section color-band"><div class="container visual-split"><div><p class="eyebrow">Why Choose Us</p><h2>Revenue comes from AI use-case planning, automation delivery, analytics, and operational intelligence work.</h2><p>Teams with scattered reporting, manual processes, inconsistent data, limited visibility, or AI interest that needs practical use cases and controlled implementation.</p><div class="mini-proof"><article><strong>Better decisions</strong><span>Outcome-focused support.</span></article><article><strong>Less repetitive work</strong><span>Outcome-focused support.</span></article><article><strong>Clearer reporting</strong><span>Outcome-focused support.</span></article></div></div><figure class="visual-card"><img src="<?= e(asset('images/trust-visual.svg')) ?>" alt="DatastAIsis trust visual" loading="lazy"></figure></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="DatastAIsis process visual" loading="lazy"></figure><div><p class="eyebrow">Process</p><h2>Simple enough to start, structured enough to scale.</h2><div class="process-grid compact"><article><span>01</span><h3>Identify use cases</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Map data sources</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Prioritize automation</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Build insight workflows</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section related-solutions"><div class="container"><div class="section-heading centered"><p class="eyebrow">Related BTP Solutions</p><h2>Connected support across the BTP ecosystem.</h2></div><div class="related-grid"><article class="related-card"><p class="eyebrow">CodeIGNITE</p><h3>Software development and application engineering for platform innovation.</h3><a href="https://codeignite.cloudexcelon.com/">BTP CodeIGNITE <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">CloudEXCELON</p><h3>Cloud architecture and infrastructure built for scalable enterprise environments.</h3><a href="https://dev.cloudexcelon.com/">BTP CloudEXCELON <span aria-hidden="true">&rarr;</span></a></article><article class="related-card"><p class="eyebrow">SecuriSCOPE</p><h3>Cybersecurity strategy, protection, compliance, and resilience for enterprise environments.</h3><a href="https://securiscope.cloudexcelon.com/">BTP SecuriSCOPE <span aria-hidden="true">&rarr;</span></a></article></div></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Step</p><h2>Ready to make the technology path clearer?</h2><p>BTP DatastAIsis helps organizations structure data, automate repetitive workflows, build analytics, and apply AI to improve decisions and business outcomes.</p></div><a class="button button-primary" href="/contact">Plan an AI and Data Session <span aria-hidden="true">&rarr;</span></a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
