<?php
$pageTitle = 'BTP DatastAIsis Services | AI, automation, analytics, and operational intelligence for business outcomes.';
$metaDescription = 'Explore BTP DatastAIsis capabilities, deliverables, engagement process, and business outcomes.';
$pagePath = '/services';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>DatastAIsis Services</h1><p>AI, automation, analytics, and operational intelligence for business outcomes.</p></div></section>
<section class="section"><div class="container visual-split"><div><p class="eyebrow">Overview</p><h2>AI, automation, and analytics that turn scattered work into operational intelligence.</h2><p>BTP DatastAIsis helps organizations structure data, automate repetitive workflows, build analytics, and apply AI to improve decisions and business outcomes.</p><p><strong>Who it helps:</strong> Teams with scattered reporting, manual processes, inconsistent data, limited visibility, or AI interest that needs practical use cases and controlled implementation.</p></div><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="DatastAIsis service visual" loading="lazy"></figure></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Summarized clearly for faster evaluation.</h2></div><div class="detail-grid compact"><article class="detail-card"><span class="service-icon">AS</span><h3>AI solutions</h3><p>Data and automation opportunity map</p></article><article class="detail-card"><span class="service-icon">DA</span><h3>Data analytics</h3><p>Use-case prioritization</p></article><article class="detail-card"><span class="service-icon">WA</span><h3>Workflow automation</h3><p>Dashboard or reporting plan</p></article><article class="detail-card"><span class="service-icon">BI</span><h3>Business intelligence</h3><p>Automation workflow design</p></article><article class="detail-card"><span class="service-icon">WO</span><h3>Workflow optimization</h3><p>AI implementation roadmap</p></article><article class="detail-card"><span class="service-icon">DS</span><h3>Data strategy</h3><p>Data and automation opportunity map</p></article></div></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="DatastAIsis engagement visual" loading="lazy"></figure><div><p class="eyebrow">Engagement Process</p><h2>How BTP moves from need to next step.</h2><div class="process-grid compact"><article><span>01</span><h3>Identify use cases</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Map data sources</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Prioritize automation</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Build insight workflows</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section trust-band"><div class="container proof-grid"><article><strong>Better decisions</strong><span>Outcome-focused support.</span></article><article><strong>Less repetitive work</strong><span>Outcome-focused support.</span></article><article><strong>Clearer reporting</strong><span>Outcome-focused support.</span></article><article><strong>Practical AI adoption</strong><span>Outcome-focused support.</span></article></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Steps</p><h2>Discuss the service path that fits your environment.</h2><p>Bring your current goals, constraints, vendors, systems, or project questions. BTP will help clarify the path forward.</p></div><a class="button button-primary" href="/contact">Plan an AI and Data Session</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
