<?php
$pageTitle = 'BTP CodeIGNITE Services | Software development and application engineering for platform innovation.';
$metaDescription = 'Explore BTP CodeIGNITE capabilities, deliverables, engagement process, and business outcomes.';
$pagePath = '/services';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">BTP Innovations</p><h1>CodeIGNITE Services</h1><p>Software development and application engineering for platform innovation.</p></div></section>
<section class="section"><div class="container visual-split"><div><p class="eyebrow">Overview</p><h2>Software engineering for applications, platforms, workflows, and modernization.</h2><p>BTP CodeIGNITE helps organizations design, build, modernize, integrate, and improve software that supports operations, customer experience, automation, and platform growth.</p><p><strong>Who it helps:</strong> Businesses with workflows that outgrew spreadsheets, legacy platforms that slow teams down, integration gaps between systems, or product ideas that need disciplined engineering.</p></div><figure class="visual-card"><img src="<?= e(asset('images/hero-visual.svg')) ?>" alt="CodeIGNITE service visual" loading="lazy"></figure></div></section>
<section class="section muted"><div class="container"><div class="section-heading centered"><p class="eyebrow">Services</p><h2>Summarized clearly for faster evaluation.</h2></div><div class="detail-grid compact"><article class="detail-card"><span class="service-icon">SD</span><h3>Software development</h3><p>Product discovery brief</p></article><article class="detail-card"><span class="service-icon">WA</span><h3>Web applications</h3><p>Technical architecture</p></article><article class="detail-card"><span class="service-icon">MA</span><h3>Mobile applications</h3><p>UX and workflow plan</p></article><article class="detail-card"><span class="service-icon">EP</span><h3>Enterprise platforms</h3><p>Development roadmap</p></article><article class="detail-card"><span class="service-icon">AI</span><h3>API integration</h3><p>Deployment and improvement backlog</p></article><article class="detail-card"><span class="service-icon">A</span><h3>Automation</h3><p>Product discovery brief</p></article></div></div></section>
<section class="section process-band"><div class="container visual-split reverse"><figure class="visual-card"><img src="<?= e(asset('images/process-visual.svg')) ?>" alt="CodeIGNITE engagement visual" loading="lazy"></figure><div><p class="eyebrow">Engagement Process</p><h2>How BTP moves from need to next step.</h2><div class="process-grid compact"><article><span>01</span><h3>Clarify the workflow</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>02</span><h3>Design the solution</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>03</span><h3>Build the platform</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article><article><span>04</span><h3>Integrate systems</h3><p>A focused step that keeps decisions, owners, and next actions visible.</p></article></div></div></div></section>
<section class="section trust-band"><div class="container proof-grid"><article><strong>Useful business software</strong><span>Outcome-focused support.</span></article><article><strong>More efficient workflows</strong><span>Outcome-focused support.</span></article><article><strong>Stronger platform foundations</strong><span>Outcome-focused support.</span></article><article><strong>Faster iteration</strong><span>Outcome-focused support.</span></article></div></section>
<section class="section final-cta"><div class="container cta-card"><div><p class="eyebrow">Next Steps</p><h2>Discuss the service path that fits your environment.</h2><p>Bring your current goals, constraints, vendors, systems, or project questions. BTP will help clarify the path forward.</p></div><a class="button button-primary" href="/contact">Discuss Your Project</a></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
